// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PREPARAES.Models;

namespace PREPARAES.Migrations
{
    [DbContext(typeof(PreparaesContext))]
    [Migration("20181207223809_TablaReformado")]
    partial class TablaReformado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PREPARAES.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ciclo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PREPARAES.Models.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PreguntaString")
                        .IsRequired();

                    b.Property<string>("RptaCorrecta")
                        .IsRequired();

                    b.Property<string>("RptaIncorrecta1");

                    b.Property<string>("RptaIncorrecta2");

                    b.Property<int>("SesionId");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("PREPARAES.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CursoId");

                    b.Property<int>("NumSesion");

                    b.Property<string>("Objetivos");

                    b.Property<string>("Tema");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("PREPARAES.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApellidoM");

                    b.Property<string>("ApellidoP");

                    b.Property<string>("Correo");

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PREPARAES.Models.Curso", b =>
                {
                    b.HasOne("PREPARAES.Models.Usuario", "Usuario")
                        .WithMany("Cursos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PREPARAES.Models.Pregunta", b =>
                {
                    b.HasOne("PREPARAES.Models.Sesion", "Sesion")
                        .WithMany("Preguntas")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PREPARAES.Models.Sesion", b =>
                {
                    b.HasOne("PREPARAES.Models.Curso", "Curso")
                        .WithMany("Sesiones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
