// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PREPARAES.Models;

namespace PREPARAES.Migrations
{
    [DbContext(typeof(PreparaesContext))]
    partial class PreparaesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PREPARAES.Models.Cursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ciclo");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PREPARAES.Models.Preguntas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pregunta")
                        .IsRequired();

                    b.Property<string>("RptaCorrecta")
                        .IsRequired();

                    b.Property<string>("RptaIncorrecta1");

                    b.Property<string>("RptaIncorrecta2");

                    b.Property<int>("SesionId");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("SesionId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("PREPARAES.Models.Sesiones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CursoId");

                    b.Property<int>("NumSesion");

                    b.Property<string>("Objetivos");

                    b.Property<string>("Tema");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("PREPARAES.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApellidoM");

                    b.Property<string>("ApellidoP");

                    b.Property<string>("Correo");

                    b.Property<string>("Nombre");

                    b.Property<string>("password");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PREPARAES.Models.Cursos", b =>
                {
                    b.HasOne("PREPARAES.Models.Usuarios", "Usuario")
                        .WithMany("Cursos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PREPARAES.Models.Preguntas", b =>
                {
                    b.HasOne("PREPARAES.Models.Sesiones", "Sesion")
                        .WithMany("Preguntas")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PREPARAES.Models.Sesiones", b =>
                {
                    b.HasOne("PREPARAES.Models.Cursos", "Curso")
                        .WithMany("Sesiones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
